eclipse-elk/elk

plugins/org.eclipse.elk.gmf/src/org/eclipse/elk/gmf/GmfDiagramLayoutManager.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=485905
- Use a protected method to access the DiagramEditor to improve
extensibility
Change-Id: I9f5d0d503297589b1171e14e346556bc9512fd32
Signed-off-by: Camille Letavernier <camille.letavernier@cea.fr>

Bug 485905: [GMF Connector] Make the GMF Connector more extensible

---

plugins/org.eclipse.elk.graph/model/kgraph.ecore
plugins/org.eclipse.elk.graph/model/kgraph.genmodel
plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/KGraphPackage.java
plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/util/KGraphSwitch.java

The ecore model still uses the old namespace, leading to broken code when generating new model files for this project or projects depending on the kgraph.
Signed-off-by: Nis Boerge Wechselberg <nbw@informatik.uni-kiel.de>

elk.graph: Migrated ecore namespace to eclipse

---

plugins/org.eclipse.elk.alg.layered/src-gen/org/eclipse/elk/alg/layered/properties/LayeredMetaDataProvider.java
plugins/org.eclipse.elk.alg.layered/src-gen/org/eclipse/elk/alg/layered/properties/LayeredOptions.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.elkm
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/splines/SplineEdgeRouter.java

The new option reduces the number of spline control points in the spline
edge routing phase. Edge segments connected to normal nodes are routed
on a direct path instead of following the orthogonal edge bend points.
This new option is activated by default.

elk.layered.splines: Introduced new option for sloppy spline routing.

---

plugins/org.eclipse.elk.alg.force/src-gen/org/eclipse/elk/alg/force/properties/ForceMetaDataProvider.java
plugins/org.eclipse.elk.alg.graphviz.layouter/src-gen/org/eclipse/elk/alg/graphviz/layouter/GraphvizMetaDataProvider.java
plugins/org.eclipse.elk.alg.layered/src-gen/org/eclipse/elk/alg/layered/properties/LayeredMetaDataProvider.java
plugins/org.eclipse.elk.core/src-gen/org/eclipse/elk/core/options/CoreOptions.java

The current version of elkm doesn't generate simple types in the
registration codes anymore. Instead it writes the boxed types now.

Metadata: Updated generated code from elkm files.

---

plugins/org.eclipse.elk.alg.layered/src-gen/org/eclipse/elk/alg/layered/properties/LayeredMetaDataProvider.java
plugins/org.eclipse.elk.alg.layered/src-gen/org/eclipse/elk/alg/layered/properties/LayeredOptions.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.elkm
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/splines/SplineEdgeRouter.java

When using sloppy spline routing some additinoal space between layers
can be desired to produce better curves. The new option introduces a
spacing factor to limit the steepness between layers.
The calculation of the space between layers is adapted from the polyline
routing.
In addition a bug in the spline router is fixed, that caused improper
routing when using bignodes.

layered.splines: Improved layer spacing in sloppy spline routing

---

plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/intermediate/LevelHeightProcessor.java
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/p3place/NodePlacer.java

Mr.Tree pitied the nodes in the layers, so he decided to potentially
give them way too much space in the layers.
The calculation of the layer heights is corrected and the spacing
between layers is also correct now.
This fixes issue #45 

Fixed level height usage in Mr.Tree

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/compound/CompoundGraphPreprocessor.java

Unconnected external ports were potentially placed on wrong sides of the
parent node. (#48)
Passing the parent node port constraints to the new external port dummy.

Layered: Fixed handling of FIXED_SIDE with INCLUDE_CHILDREN

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/splines/SplineEdgeRouter.java

With sloppy spline routing there were some cases were edges could
intersect with nodes. This happened when nodes in one layer had
different sizes. The change introduces additional control point at the
start or end of the layer if the node does not cover the complete width
of the layer.

layered.splines: Reduced spline edge/node intersections

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/HyperedgeDummyMerger.java

Different Hyperedges were incorrectly merged when there were labels in
both edges. This was caused by allowing merging of edges with null set
as source or target. The change makes the code conform to the comment
that enforces both target and source be not null.
This should fix issue #96 

elk.layered: Fix hyperedge merging with label dummies

---

setups/EclipseLayoutKernel.setup

After performing the Oomph setup I had errors in the connector bundles due to missing dependencies in the target platform. I changed the GMF dependency to `org.eclipse.gmf.sdk.feature.group` ("Graphical Modeling Framework (GMF) Tooling SDK") and then it worked. This one includes the Runtime and Notation SDKs.

[oomph] Changed GMF dependency to org.eclipse.gmf.sdk.feature.group

---

plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/LayoutConfigurationManager.java
plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/views/LayoutPropertySource.java

The layout view created ArrayIndexOutOfBoundsExceptions when changing
the selection in diagrams. This was caused by us creating a list of all
available layout options and therefore creating duplicate entries when
multiple targets were allowed. The PropertyView uses sets for the
properties and was creating the exceptions.
This change gets rid of the lists and uses a set instead to prepare the
layout options for the property view.

layoutview: Changed layout option collection from lists to set

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/BoxLayoutProvider.java

In normal mode the BoxLayouter used to duplicate all paddings when
resizing the parent node. This lead to excessive space at the right and
bottom.
The other modes tripled the paddings and placed the child nodes at
double the needed spacing. 

elk.box: Correct handling of padding

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/GraphTransformer.java

When layouting down or up and setting a minimal node size, the minimum
node size was not properly transposed, leading to broken layouts.

layered.transform: Fixed broken handling of minimal size

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

When using BoxLayout with expand nodes activated, the edges were not
properly adjusted.

core.ElkUtil: Fixed translation of edges during node translation

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java

The processing of end labels was not working due to the graph not being
layered anymore after the HierarchicalNodeResizeProcessor. The change
schedules the EndLabelProcessor before the HierarchicalNodeResizeProcessor.

elk.layered: Fixed end label processing

---

docs/layouts/partials/nav.html

The relative link caused a 404 because there was an extra /elk/ in the url.

Site: Fixed incubation link

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java

The junction points of inside self loops need to be properly offset.
Fixes #168 

core.layoutEngine: Offset Inside Self Loop Junction Points

---

plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/TreeUtil.java
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/intermediate/LevelHeightProcessor.java
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/intermediate/NeighborsProcessor.java

Guava deprecated (and removed) the method emptyIterator().
Instead Collections.emptyIterator() should be used.

mrtree: Removed usage of deprecated Iterators.emptyIterator()

---

setups/EclipseLayoutKernel.setup

The recent change to the required xtext version (#183) also incremented
the versions for already released version streams. This is probably not
a good idea.

setup: Reverted version dependencies of old release streams

---

plugins/org.eclipse.elk.graph.text.ui/src/org/eclipse/elk/graph/text/ui/ConvertGraphHandler.java
plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/util/GraphIdentifierGenerator.java

Previously, a graph could be converted into ELKT format with graph element identifiers that did not comply to ELKT's ID rule. Now, these identifiers can be automatically fixed.

Graph: Graph converter now fixes invalid characters. #197

---

plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonExporter.xtend

Edge sections lack bend point data even if layout should be preserved.

graph.json: Added bend points to exported data

---

plugins/org.eclipse.elk.graph.text/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/ElkGraphRuntimeModule.xtend
plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/linking/ElkGraphLinker.xtend
plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/validation/ElkGraphValidator.xtend

This is an alternative solution for #170. I expect this one to cause fewer follow-up problems compared to the original solution.
@uruuru could you check whether the parsed models are properly linked with this change?

Explicitly list opposite references that must not be cleared in ElkGraph linker

---

plugins/org.eclipse.elk.alg.common.compaction/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.force/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.graphviz.dot/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.graphviz.layouter/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.layered/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.mrtree/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.radial/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.conn.gmf/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.conn.graphiti/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.debug/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.meta.ui/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.meta/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.service/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.ui/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core/.classpath
plugins/org.eclipse.elk.core/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.graph.json/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.graph.text.ide/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.graph.text.ui/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.graph.text/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.graph/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.alg.common.compaction.test/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.alg.test/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.core.test/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.graph.json.test/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.graph.test/.settings/org.eclipse.jdt.core.prefs
test/org.eclipse.elk.shared.test/.settings/org.eclipse.jdt.core.prefs

This makes sure that the projects are built with the correct compiler settings even when they are imported into a workspace that has not been generated by Oomph.

Added project-specific JDT settings

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/splines/SplineEdgeRouter.java

End labels were broken with splines because the processor configuration
was misconfigured. This is now fixed.

layered: Fixed tail label placement with splines

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

Since the new graph structure, the fixed layouter wasn't able
to create junction points any more. The corresponding utility
function has been modified to allow for potentially
mismatched coordinate systems due to different containments.

ElkUtil: Reactivated Junction Point detection for fixed layout

---

test/org.eclipse.elk.alg.spore.test/META-INF/MANIFEST.MF

All the other bundles use only a minimum version restriction for Guava.
Let's do it similarly in this bundle to avoid version conflicts when
upgrading to a target that contains only Guava 21.
I got a compile error here when using a custom target platform which does not contain Guava 18 anymore.
Signed-off-by: Michael Keppler <Michael.Keppler@gmx.de>

remove version restriction on Google Guava

---

plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/GmfDiagramLayoutConnector.java
plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/GmfLayoutSetup.java

- Added a verification to know if the manipulated editor is IAdaptable and get its associated DiagramEditor if any
Signed-off-by: Quentin Le Menez <quentin.lemenez@cea.fr>

conn.gmf: Fix to allow Papyrus' MultidiagramEditors

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PortListSorter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/PortSortingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/SweepCopy.java

Try to preserve the input graph's edge order up to the point where the internal graph is passed to the crossing minimization. The goal is that (if it doesn't matter from the crossing minimization's perspective) the drawing reflects the edge order. 
For this, the graph import had to be altered to iterate `#getContainedEdges` instead of each node's outgoing edges. 
Please double-check the inside self loop handling.

Somewhat preserve the input graph's edge order 

---

plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/rendering/GraphRenderer.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/ElkMath.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/KVectorChain.java

The GraphRenderer used to draw spline edges using an approximation, which looked ugly because the resulting points had to be casted to `int`. With this change, the `drawPath(..)` method of GC is used, which yields nicely curved spline edges.

Render real splines in GraphRenderer

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SelfLoopPreProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/loops/SelfLoopComponent.java

* Fixes #407 by creating SelfLoopLabels only for edges that are actually self-loops.
* Simplified the code of `SelfLoopComponent.createSelfLoopComponents(SelfLoopNode)`.

Create SelfLoopLabels only for edges that are actually self-loops

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/validation/LayoutOptionValidator.java
plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/impl/EMapPropertyHolderImpl.java

Without these guards, NullPointerExceptions can fly around when you try to process a graph with references to unknown properties, e.g. after loading it from an `elkt` file.

Added null guards for IPropertyValueProxy processing

---

plugins/org.eclipse.elk.alg.disco.debug/build.properties

- Added the icons folder into the build.properties
Signed-off-by: Quentin Le Menez <quentin.lemenez@cea.fr>

alg.disco.debug: The View icon is not displaying properly

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutAlgorithmResolver.java
test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/RecursiveGraphLayoutEngineTest.java

This pull request changes the way `LayoutAlgorithmResolver` handles the case when layout algorithm resolution fails. It tries the default algorithm only if no algorithm was specified. If an algorithm was specified, but fails to resolve, this is now treated as an error since that is most certainly not what the user wanted.

Change how layout algorithms are resolved

---

plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPacking.melk
plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPackingLayoutProvider.java
plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/Compaction.java

The parent node is correctly resized.
The algorithm logs intermediate graphs.
Compaction was optimized. If a row is emptied this is taken into account.

Fixed problems with rect packing algorithm

---

plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/ElkServicePlugin.java

... because loading class 'AbstractUIPlugin' seems to require SWT (esp. 'SWTError') on the classpath that may not be available in standalone scenarios;
Copied 'IPreferenceStore' provision from 'AbstractUIPlugin'
To my surprise this change is also required in the standalone context,
otherwise failures (java.lang.Error) may happen at locations like this
https://github.com/eclipse/elk/blob/524db6178cec3e06c57c936e39b6f1f00363bf44/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java#L63-L65
This also looks like such a candidate:
https://github.com/eclipse/elk/blob/883c156b7986392bede639fd479e13c6a2c5e451/plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/DiagramLayoutEngine.java#L536-L537

Service: changed super class of 'ElkServicePlugin' from 'AbstractUIPlugin' to just 'Plugin'

---

test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/InLayerConstraintProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/InvertedPortProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LabelDummyRemoverTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LabelSideSelectorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LayerSizeAndGraphHeigthCalculatorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LongEdgeJoinerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LongEdgeSplitterTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodeMarginCalculatorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodePromotionTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PortListSorterTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PortSideProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/ReversedEdgeRestorerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p1cycles/BasicCycleBreakerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p2layers/BasicLayerAssignmentTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p4nodes/BasicNodePlacementTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p5edges/BasicEdgeRouterTest.java
test/org.eclipse.elk.alg.test/src/org/eclipse/elk/alg/test/framework/graph/GraphFromFile.java

The elkg are identical to the elkt (graph-wise). The idea behind checking in the elkg as well is to significantly reduce the execution time of ELK's unit tests. Parsing the xtext-based elkt files takes very long, especially for larger models.

Switch unit tests to using elkg instead of elkt for ptolemy models

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPackingLayoutProvider.java

If a position constraint is set that is bigger than the number of nodes the node is added to the end of the list.

Rectpacking: Handle too big position constraints.

---

build/pom.xml

The parameter is available since 1.5.0 and we're using 1.6.0 by now.

build: use 'enableAssertions' for tycho surefire

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java

I removed the `legacyIds` part from the xtext grammar but did not push the re-generated code.
The workflow finishes successfully but there are several changes - most of them are comment or formatting only changes, though. 
I'd suggest to wait for a larger grammar change before re-generating the code.

Fixes #577 (remove legacyIds)

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/compaction/Polyomino.melk
plugins/org.eclipse.elk.alg.disco/src/org/eclipse/elk/alg/disco/Disco.melk
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/Force.melk
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/stress/Stress.melk
plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/Graphviz.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/Tree.melk
plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/Radial.melk
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPacking.melk
plugins/org.eclipse.elk.alg.spore/src/org/eclipse/elk/alg/spore/SPOrE.melk
plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/layouter/Gmf.melk
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/formatting2/MetaDataFormatter.xtend
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/labels/Labels.melk

I slightly altered the formatter (without changing the out-of-conventions coding style of the class):
- no space between layout algorithm id and its implementing class
- two newlines between groups, options, etc.
- indent text to 'description' of categories, options, and algorithms
- no space before commas
Afterwards I reformatted all of the `*.melk` files. One major change is that tabs are replaced by spaces (although that's an editor configuration). 
Anything that feels awkward?
Note that the changes of the formatter are not available within the main eclipse until a new version has been deployed and installed.

Fix #579 (formatting melk)

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk

The default value in `Core.melk` is already `20`. And since we're not explicitly setting default values for the other inherited spacing options, I suggest to be consistent and remove it for `nodeNode`.

layered: removed superfluous default on spacing.nodeNode

---

plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/jvmmodel/MelkDocumentationGenerator.xtend

I tested it locally and the generated *.md files look fine:
```
*Value Type:* | `org.eclipse.elk.core.options.PortSide` (Enum)
*Possible Values:* | `EAST`<br>`NORTH`<br>`SOUTH`<br>`UNDEFINED`<br>`WEST`
*Default Value:* | `PortSide.UNDEFINED` (as defined in `org.eclipse.elk`)
```
For me the order of the enum values does not match the order within the source file though. However, it doesn't match with the original code (and my local setup) either. 
Maybe linux java preserves the order by chance?

[PR] melk.doc: properly extract enum literals #604

---

plugins/org.eclipse.elk.graph.text.ide/src/org/eclipse/elk/graph/text/ide/contentassist/ElkGraphProposalProvider.xtend

For a `null` argument, the properties proposed now includes properties for all possible targets, not for none.
Signed-off-by: Christoph Daniel Schulze <cds@informatik.uni-kiel.de>

Graph Text: Change default property proposal mechanism.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayeredSpacings.java
plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/DiagramLayoutEngine.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/LayoutConfigurator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkSpacings.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/LayeredSpacingTest.java
test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/alg/SpacingConfigurationTest.java

Efforts in the direction of #105.
The new class `ElkSpacings` is intended to be used by layout algorithm-integrators to configure a graph with spacing values before the graph is passed to the layout algorithm itself. It supports the spacing options provided by `CoreOptions`. 
The `LayeredSpacings` class adjusts and extends the functionality of `ElkSpacings` by what layered offers in terms of additional spacing options (in particular the _between layers_ options). 
Furthermore, there's a new layout option in `Layered.melk`: `spacing.baseValue`. It can be used to alter the overall "spaciousness" of a drawing. In other words, in can in-/decrease _all_ spacing values. If one desires to fine-tune individual spacing option values, the `LayeredSpacings` class would have to be used manually as …

[PR] Convenient spacing configuration

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

I don't see any reason why it should be programmatic: as soon as port constrains are fixed order, these values can be used to specify the order.

Removed 'programmatic' from 'port.index'

---

build/org.eclipse.elk.targetplatform/org.eclipse.elk.targetplatform.target
setups/EclipseLayoutKernel.setup

- include 'hamcrest.library' (it's part of the orbit drops update site)
- add 'includeSource = true' (so far no source was available for guava etc., which is annoying)
- removed (hopefully) unneccesary xtext 2.1.1 dependency (afair the antlr part is automatically downloaded for mwe execution) 
Note that the `*.target` is generated by oomph.

build: updated target platform

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeMarginCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/NodeContext.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/PortContext.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/HorizontalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/InsidePortLabelCellCreator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/NodeLabelAndSizeUtilities.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/PortContextCreator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/PortLabelPlacementCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/VerticalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/compound/CompoundGraphPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/HierarchicalPortOrthogonalEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelAndNodeSizeProcessor.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/DeprecatedLayoutOptionReplacer.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/NodeLabelPlacement.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/PortLabelPlacement.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/SizeOptions.java
test/org.eclipse.elk.alg.common.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.common.test/src/org/eclipse/elk/alg/common/nodespacing/NextToPortLabelPlacementTest.java
test/org.eclipse.elk.alg.common.test/src/org/eclipse/elk/alg/common/nodespacing/PortLabelPlacementVariantsTest.java
test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/data/DeprecatedLayoutOptionReplacerTest.java

See #626. 
It probably makes sense to go through the PR commit by commit. 
There's one `TODO` open: where to implement the legacy behavior (see comment in code). 
While working on this (and in particular while writing the test), I found the behavior rather inconsistent: 
* inside and outside behave differently by default (inside even behaves differently for non- and hierarchical edges) 
* always same side and space efficient do not apply to inside labels 
* north/south behaves differently by default
I'd suggest to create another issue for this, though.

[PR] Streamlined port label placement

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPreprocessor.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LabelSideSelectorTest.java

This pull request removes an assertion which is supposed to check whether a node's port list is properly ordered. However, at the time the assertion is checked, it is hard to define exactly what "properly ordered" means as that depends on a whole lot of factors:
* The node's original port constraints.
* Port sides, positions and indices.
* Hidden and re-inserted ports.
* Dummy ports.
I think it's easier to simply remove the assertion and trust that the port lists are properly sorted instead of making the assertion code unnecessarily complex.

[PR] Layered: Remove problematic assertion. #599

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeMarginCalculator.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodeMarginCalculatorTest.java

When I looked into #616, I noticed that the culprit was always the `InnermostNodeMarginCalculator`, which in turn calls the `NodeMarginCalculator`. I thus fixed the issue there. If you feel like we should add the same fix to the other node margin code, I can do that as well.

[PR] Alg: Fix negative node margins. #616

---

test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/InLayerConstraintProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/InvertedPortProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LabelDummyRemoverTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LayerSizeAndGraphHeigthCalculatorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LongEdgeJoinerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/LongEdgeSplitterTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodeMarginCalculatorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodePromotionTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PortListSorterTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PortSideProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/ReversedEdgeRestorerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p1cycles/BasicCycleBreakerTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p2layers/BasicLayerAssignmentTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p4nodes/BasicNodePlacementTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p5edges/BasicEdgeRouterTest.java

The build is going to be failing, I'll use this PR to track the issues. 
```
2020-04-21T16:35:59.0873424Z Running org.eclipse.elk.alg.layered.intermediate.NodeMarginCalculatorTest
2020-04-21T16:36:03.7706361Z Tests run: 550, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.689 s <<< FAILURE! - in org.eclipse.elk.alg.layered.intermediate.NodeMarginCalculatorTest
```
In both cases `assertTrue(node.getMargin().bottom >= 0);` fails. 
The issue is in both cases due to double imprecision:
```
-1.4210854715202004E-14
-1.4210854715202004E-14
```
```
2020-04-21T16:36:08.6396228Z Running org.eclipse.elk.alg.layered.intermediate.LabelSideSelectorTest
2020-04-21T16:36:14.2256751Z Tests run: 550, Failures: 29, Errors: 0, Skipped: 0, Time elapsed: 5.591 s <<< FAILURE! - in …
```

[PR] Test: added hierarchical test cases

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/ConstraintsPostprocessor.java

Usually the naming convention during camel case is to capitilize only
the first letter of things such as "ID" etc.
Also, it fits the melk code generator better.
(The removed imports seem to have been relicts)

[PR] Rename options *ID -> *Id

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/wrapping/CuttingUtils.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/Spacings.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutOptionData.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/IndividualSpacings.java
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonExporter.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/IndividualSpacingsTest.xtend

Light version of #629, addressing #620: allows to specify the individual spacings via a plain string. I.e. no formatting and content assist within `elkt`. But better than nothing 🙄. 
```
spacing.portPort: 5
node n1 {
spacing.individual: "spacing.portPort: 10"   
port p1
port p2 
}
node n2 {
port p1
port p2 
}
```

[PR] Basic individual spacings in elkg and elkt

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PartitionMidprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PartitionPostprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PartitionPreprocessor.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PartitionPostProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/PartitionTest.java

I fixed the problem by making sure before cycle breaking that all edges that cross layout partitions point from lower to higher partitions. Then, before layering, I do what we previously did before cycle breaking: add edges from nodes in lower partitions to nodes in higher partitions. Those edges are immediately removed again after layer assignment, as we already did previously.
This approach does not work with arbitrary graphs that don't assign layout partitions to all nodes. If no partition-crossing edge is part of a cycle with non-partitioned nodes, it should work. Once that property is not satisfied, we might run into cases where cycle breaking reverses edges between partitioned nodes such that those edges point in the wrong direction. While there certainly are ways to fix that, I …

[PR] Layered: Fix cycles breaking layout partitions. #656

---

plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend

Deciding on a default behavior for `edgeLabels.placement` is not really a task the json importer should perform. 
Without specifying anything on a json label itself, the exported elkt node and edge labels get `edgeLabels.placement: CENTER`.
```
{
"id": "root",
"children": [
{
"id": "B",
"labels": [ { "text": "B" } ],
"width": 20,
"height": 20
}
]
}
```
```
graph root
node B {
layout [ size: 20, 20 ]
label "B" {
edgeLabels.placement: CENTER
}
}
```

Don't set edge placement during JsonImport if undefined

---

test/org.eclipse.elk.alg.test/src/org/eclipse/elk/alg/test/PlainJavaInitialization.java
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/ExportTest.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/GraphTest.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/IndividualSpacingsTest.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/LayoutOptionsTest.xtend

One test in `graph.json.test` failed after, for unknown reasons, the execution order of the unit tests during CI changed. 
The issue seemed to be that `LayeredOptions` had not been registered properly at the point of failure. 
So far I'm not aware of the root cause. However, I cleaned the tests a bit to prevent registering the layout options over and over again, which seems to fix the tests again (for now 🙄).

[PR] Prevent repeated registration of layout options during PlainJavaInitialization

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphUtil.java
test/org.eclipse.elk.alg.layered.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue680Test.java

Fixes #680.
- Enlarge external port dummies when port border offset is negative (i.e. the port reaches into the node)
- Apply symmetric fix from #595 to NORTH side ports

[PR] Fix external port positioning

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeLabelAndSizeCalculator.java

Previously, due to the way `Direction#isHorizontal()` and `Direction#isVertically()` are implemented (simply ignoring `UNDEFINED`), an undefined layout direction resulted in a horizontal stacking of labels: left-to-right. 
As I feel vertically stacking is the more natural choice, I changed the behavior for undefined. 
Note that for layered the direction is _always_ right (internally during node label placement). For other layouters it can happen though that the direction is undefined as they do not support the option at all. 
That being said, I tend to suggest to use a different layout option to decide on the stacking dimension than the layout direction.

[PR] Change default node label stacking dimension for Direction.UNDEFINED

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java

... otherwise it can happen that suffixes are not unique.

Clear suffix cache when new layout options have been registered

---

plugins/org.eclipse.elk.core.service/pom.xml

`org.eclipse.urischeme` depends on `com.sun.jna` in its latest version. The latter is not available on maven central though. 
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=567244

Build workaround for broken eclipse.urischeme dependency 

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

[PR] Core: Node label padding now targets parents instead of nodes. #684

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeLabelAndSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/cellsystem/StripContainerCell.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/HorizontalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/InsidePortLabelCellCreator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/NodeLabelAndSizeUtilities.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/VerticalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/compound/CompoundGraphPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/adapters/ElkGraphAdapters.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue701Test.java
test/org.eclipse.elk.alg.test/src/org/eclipse/elk/alg/test/GraphTestUtils.java

#701: These commits do not cover all the cases. There are some remaining "TODO" in the code or in the test. But they clearly improve the behavior for fixed labels of port. Some tests can also be completed for #638 (more or less linked to #701).
I push this state because I'm not sure to can allow more time on it.

#701: Handle spacing for port labels with fixed location

---

setups/EclipseLayoutKernel.setup

As suggested by @uruuru in #772, this updates the eclipse download URL so that you can set up locally with the Eclipse Installer

Update Eclipse Setup Download URL

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderNodeComparator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/CycleBreakingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p1cycles/ModelOrderCycleBreaker.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/BasicConsiderModelOrderTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p1cycles/BasicCycleBreakerTest.java

Added a cycle breaker that reverses edges going against the model order.
Edges should always go from low model order to high model order.

layered: Added model order cycle breaker.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java

Simply set the model order when importing a graph (also for hierarchical graphs).

layered: Assign model order on import of hierarchical graphs. fixes #724

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/LayoutConfigurator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

Fixes #781 in two ways:
* Always clone property values when applying a `LayoutConfigurator`
* Clone the `NODE_SIZE_MINIMUM` value so it can be safely modified
Both changes independently fix the concrete example given in #781, and in both cases the result looks like this:
_Note:_ I chose not to throw an exception in case cloning the value fails (cf. `Property#getDefault()`) to avoid potentially breaking existing applications.

Clone properties to avoid sharing mutable values in multiple elements

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderPortComparator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java

When comparing ports, backward edges are always ordered below and are not taken into account for order inheritance, which only focuses on the "real" outgoing edges of the current node.

Handle backward edges to not produce order violations that do not exist.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/compound/CompoundGraphPreprocessor.java

For any other spacing edges and port dummies have no size. However, external port dummies are configured to have the size of an edge which is not consistent with other spacing configurations.
Fixes #766 

Layered: Hierarchical: External port dummies have no size.

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/NodeContext.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/HorizontalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/InsidePortLabelCellCreator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/PortLabelPlacementCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/VerticalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/overlaps/GreedyRectangleStripOverlapRemover.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/overlaps/RectangleStripOverlapRemover.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/HierarchicalPortOrthogonalEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelAndNodeSizeProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayeredSpacings.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/Spacings.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/PortSide.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkSpacings.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/LayeredSpacingTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue701Test.java
test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/alg/SpacingConfigurationTest.java

Fixes #575 
Split the label port spacing in vertical spacing and horizontal spacing.
I did consider splitting it in an in-port-direction and orthogonal-to-port-direction spacing. This, however, is not consistent with other spacings and one would have to mentally turn the drawing to calculate that kind of spacing is required.

core, layered: Added individual vertical and horizontal label port spacing.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/SimpleRowGraphPlacer.java

Previously components would be ordered by the summed up priority of each
component and if no priority was set or it was equal, they were ordered
by model order. Since a summed up priority requires the user to
calculate the separate components to set this sensibly it is now
overruled by the model order.

Layered: Model order overrules priority of components.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/GraphInfoHolder.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p3order/ModelOrderBarycenterHeuristicTest.java

This fixes the issue that node model order is always enforced after this was activated once.

Fixed forced model order and added test.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/CycleBreakingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p1cycles/GreedyCycleBreaker.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p1cycles/GreedyModelOrderCycleBreaker.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p1cycles/BasicCycleBreakerTest.java

This fixes the following issue of the Greedy cycle breaker that sometimes just makes randomly wrong decisions, which can be prevented if one takes the model order into account:
Bad:
Good:

layered: Added greedy model order cycle breaker.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java

This means it should only be counted for nodes with a model order.

layered: Node order violations should only be counted for real nodes.

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/HorizontalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/InsidePortLabelCellCreator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/NodeLabelAndSizeUtilities.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/PortLabelPlacementCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/VerticalPortPlacementSizeCalculator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/PortLabelPlacement.java

See #831
This adds a new port label placement option. Namely `ALWAYS_OTHER_SAME_SIDE` that places all labels above or left instead of below and right compared to `ALWAYS_SAME_SIDE`.
Additionally, it is possible to set negative label port spacing without influencing the position of the port on the node with it.
Before:
- Negative spacing:
- Positive spacing:
After:
Model:
```
algorithm: layered
elk.direction: RIGHT
spacing.labelPortVertical: -50
spacing.labelPortHorizontal: 0
portLabels.placement: "ALWAYS_OTHER_SAME_SIDE, OUTSIDE, NEXT_TO_PORT_IF_POSSIBLE"
node n1_1 {
nodePlacement.strategy: SIMPLE
elk.direction: RIGHT
spacing.labelPortVertical: -3.3
spacing.labelPortHorizontal: 0
spacing.portPort: 1
nodeSize.constraints: "NODE_LABELS, PORT_LABELS"
portLabels.placement: …
```

Port label spacing

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPacking.melk
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/seconditeration/Compaction.java
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/seconditeration/InitialPlacement.java

This allows having more control over the whole drawing if aspect ratio and target width are not enough to control the layout.

rectpacking: Add option to place a node always at the beginning of a new row.

---

build/org.eclipse.elk.repository/category.xml
features/org.eclipse.elk.libavoid.feature/.project
features/org.eclipse.elk.libavoid.feature/build.properties
features/org.eclipse.elk.libavoid.feature/feature.xml
features/org.eclipse.elk.libavoid.feature/pom.xml
features/pom.xml
plugins/org.eclipse.elk.alg.libavoid/.classpath
plugins/org.eclipse.elk.alg.libavoid/.gitignore
plugins/org.eclipse.elk.alg.libavoid/.project
plugins/org.eclipse.elk.alg.libavoid/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.libavoid/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.libavoid/about.html
plugins/org.eclipse.elk.alg.libavoid/build.properties
plugins/org.eclipse.elk.alg.libavoid/libavoid-server/libavoid-LICENSE
plugins/org.eclipse.elk.alg.libavoid/libavoid-server/libavoid-server-LICENSE
plugins/org.eclipse.elk.alg.libavoid/pom.xml
plugins/org.eclipse.elk.alg.libavoid/src/META-INF/services/org.eclipse.elk.core.data.ILayoutMetaDataProvider
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/Libavoid.melk
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidLayoutProvider.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidPlugin.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServerException.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServerPool.java
plugins/pom.xml

This PR adds a new plug-in `org.eclipse.elk.alg.libavoid` that integrates the [libavoid](https://www.adaptagrams.org/documentation/libavoid.html) library with ELK. The plug-in is provided to the update site in a separate feature because libavoid is LGPL licensed, so not all users might want to include it.
The license check for this new dependency is approved:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24155
The Java code is taken from https://github.com/TypeFox/elk-libavoid, which in turn has been copied from the [KIELER](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Home) project by the rtsys group at Kiel University.
The Maven build downloads three binaries from https://github.com/TypeFox/libavoid-server/releases/tag/v0.1.0 which contain the actual routing …

Added org.eclipse.elk.alg.libavoid

---

docs/content/blog/posts/2022/22-11-17-libavoid.md
plugins/org.eclipse.elk.alg.libavoid/pom.xml
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/Libavoid.melk
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidLayoutProvider.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java

- Upgraded to `libavoid-server` [v0.2.0](https://github.com/TypeFox/libavoid-server/releases/tag/v0.2.0)
- Added new options `reverseDirectionPenalty` and `nudgeSharedPathsWithCommonEndPoint`
- Don't override `idealNudgingDistance` (https://github.com/eclipse/elk/pull/886#discussion_r1022634617)
- Compute port sides if they're not specified in the graph
- Compute size of parent node

Improved libavoid integration

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LNode.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelDummyRemover.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelSideSelector.java

The spacing between edges and labels should not be used for inline edge labels.
Fixes #841

layered: Center inline edge labels #841.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java

Throw exception if any child of a hierachy aware graph uses a different layer sweep method.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java

If using equals then "layered" != "org.eclipse.elk.layered".
Fixes https://github.com/kieler/elkjs/issues/178

Correctly check whether the layered algorithm is set.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p4nodes/NetworkSimplexPlacer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue870Test.java

@soerendomroes This prevents the problem from occuring and I haven't found any situations where this would cause new problems.

Fixes NoSuchElementException during Network Simplex Node Placement

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPostprocessor.java

Proposition of fix. To be checked/completed because I have absolutely no control over the impacts.
Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>

[DRAFT] Wrong tail edge label (#905)

---

plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/graph/FEdge.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/graph/FNode.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/graph/FParticle.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/model/AbstractForceModel.java

Fixes #806.
The solution works well with a limited amount of bendpoints. If they get too many, edges become intertwined.
Fixes #849.
The offset is applied to all elements (also all labels).
@Eddykasp

Added bendpoints to force layout.

---

build/pom.xml

The license was still set to EPL 1.0 for maven central.
Added me as a developer and project lead for maven central.

Correct pom for maven central

---

plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/Libavoid.melk
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidLayoutProvider.java

With micro layout
Without micro layout
With node micro layout the node labels are placed correctly.

libavoid: Added node micro layout.

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/KVector.java

Rotates the given vector v by the angle provided in radians. Rotation is anti-clockwise as is standard. The rotated vector is also returned to be consistent with the rest of the KVector methods.

Adds rotation to KVectors

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderPortComparator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/greedyswitch/TestGraphCreator.java

layered: MO save transitive dependencies when comparing ports by model order.

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/TopdownSizeApproximator.java

The original elk graph edges were being modified rather than the copies.

Fix look-ahead size approximation for top-down layout

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeSegmentSplitter.java

layered: Actually change the area index for hyperedge splitting.

---

plugins/org.eclipse.elk.alg.libavoid/pom.xml
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java

Bug fixes:
- ports were given the wrong node id's (off-by-one error)
- the hyperedge option was added as a routing option despite being handled as a normal one by the server
Changes:
- updated the libavoid server to the newest version

libavoid bug fixes

---

plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/intermediate/compaction/AbstractRadiusExtensionCompaction.java
plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/intermediate/overlaps/RadiusExtensionOverlapRemoval.java

Should fix comments in https://github.com/kieler/elkjs/issues/120

radial: Correctly use half of the node node spacing as padding.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayeringStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/DepthFirstModelOrderLayerer.java

DF and BF model order layering is experimental.
Fixes compaction bug in DF model order layering.

DF Model Order Fixes

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPackingLayoutProvider.java
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/intermediate/MinSizePostProcessor.java
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/intermediate/MinSizePreProcessor.java

Previously it was only done after because whitespace elimination might change node sizes. However, if the node size cannot fit the label, we need to do this before the layout too.
I suggest to maybe take a look at #989 and see whether this has the same reason. If both are fixed, I propose an elkjs only release for this fix.
Also fixes #996

rectpacking: Fix micro layout for rectpacking including content alignment and label placement.

---

plugins/org.eclipse.elk.alg.common/.project
plugins/org.eclipse.elk.alg.disco.debug/.project
plugins/org.eclipse.elk.alg.disco/.project
plugins/org.eclipse.elk.alg.force/.project
plugins/org.eclipse.elk.alg.graphviz.dot/.project
plugins/org.eclipse.elk.alg.graphviz.layouter/.project
plugins/org.eclipse.elk.alg.layered/.project
plugins/org.eclipse.elk.alg.libavoid/.project
plugins/org.eclipse.elk.alg.mrtree/.project
plugins/org.eclipse.elk.alg.spore/.project
plugins/org.eclipse.elk.conn.gmf/.project
plugins/org.eclipse.elk.core.service/.project
plugins/org.eclipse.elk.core.ui/.project
plugins/org.eclipse.elk.core/.project
plugins/org.eclipse.elk.graph.json/.project
plugins/org.eclipse.elk.graph/.project
test/org.eclipse.elk.alg.disco.test/.project
test/org.eclipse.elk.alg.force.test/.project
test/org.eclipse.elk.alg.radial.test/.project
test/org.eclipse.elk.alg.test/.project

The checkstyle annotations and the configuration still remain since they might be useful once we decide to reconfigure checkstyle.

Remove all checkstyle natures from all projects.

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java

This fixes a problem where the available child area would become negative if the estimated node size was very small because padding was neglected

Include padding when setting node sizes in top-down layout

---

docs/content/documentation/algorithmdevelopers/metadatalanguage.md

Correct metadata file registration docs.

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPacking.melk
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/p3whitespaceelimination/WhiteSpaceEliminationStrategy.java

Added a default value for whitespace elimination.
Additionally, I added an explicit NONE value, since null may not work as a value for all languages that utilize layout annotation.

Fix whitespace elimination is not disabled per default.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LNode.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/unzipping/GeneralLayerUnzipper.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayerUnzippingStrategy.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/GeneralLayerUnzipperTest.java

Adds a layout unzipping intermediate processor after crossing minimization

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/NorthSouthPortPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderNodeComparator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/preserveorder/ModelOrderPortComparator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LongEdgeOrderingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/ConcreteSortByInputModelTest.java

Make sure that the order of incoming ports matches the order given by the previous layer.
Updated WEST side handling to fix the main issue. Moreover, there was a p1/p2 typo as well. 
This also makes port model order non-constraining for input ports same as the edge model order.
If one wants to constrain the port order one should use portConstraints.

Fix always existing bug in model order port sorting.

---

plugins/org.eclipse.elk.alg.common/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.disco.debug/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.disco/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.force/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.layered/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.libavoid/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.mrtree/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.radial/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.rectpacking/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.spore/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.topdownpacking/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.conn.gmf/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.service/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.json/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.common.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.force.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.layered.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.spore.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.topdown.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.core.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.graph.json.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.graph.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.shared.test/META-INF/MANIFEST.MF

Re-exporting required bundles is convenient in the first place but can cause a lot of trouble on the long run.
When reexporting a required bundle that bundle effectively becomes part of the exporting bundle's API with all the consequences regarding versioning. Additionally in an OSGi runtime it can cause resolution errors if multiple versions are available.
Because of all that using reexports is not recommended and should be avoided.
This PR suggests to do that for ELK and removes all reexports and adds the therefore necessary explicit requirements instead.

Remove re-exports in MANIFEST.MF and use Import-Package where suitable

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/compaction/LGraphToCGraphTransformer.java

Self-loop labels were previously omitted during compaction. This PR moves them together with everything else.

Fixes Self-loop label bug when using compaction

---

docs/content/documentation/tooldevelopers/graphdatastructure.md

This PR fixes a simple typo in the metal model section of the docs. "modelh" -> "model"

Fix typo in meta model section

---

docs/content/blog/2024.md
docs/content/blog/posts/2024/24-12-06-layer-unzipping.md
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/IntermediateProcessorStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/unzipping/AlternatingLayerUnzipper.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayerUnzippingStrategy.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/AlternatingLayerUnzipperTest.java

- Changes the strategy from `N_LAYERS` to `ALTERNATING` to better describe the strategy.
- Improves the way properties can be set for a layer. They can now be set on any node of a layer rather than only the first node.
- Add blog post that explains the new options and links an elklive example.

Layer Splitting Improvements

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java
test/org.eclipse.elk.alg.topdown.test/src/org/eclipse/elk/alg/topdown/test/TopdownLayoutTest.java

The properties TOPDOWN_HIERARCHICAL_NODE_WIDTH and TOPDOWN_HIERARCHICAL_ASPECT_RATIO should always apply to the node they are set on rather than to their children. Prior to this change, in the NULL approximator case this was handled differently and thus led to inconsistent and confusing behaviour.

Topdown node sizes

---

test/org.eclipse.elk.alg.radial.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.spore.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.core.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.graph.json.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.graph.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.shared.test/META-INF/MANIFEST.MF

Fixes all related warnings of PDE for Java 9 or later.

Add missing module names

---

build/pom.xml

The Maven build didn't configure any JDK target level for compilation. Neither for Java code, nor for Xtext generated code. The new properties configure the Java compiler (maven.compiler.release) and the Xtext generator (if takes its default from the maven-compiler-plugin, therefore we set source/target of the compiler, even though that looks superfluous after the release property).
Fixes #1114.

Configure Maven compiler level

---

build/pom.xml

That's the Maven recommendation for the license tag, because it simplifies automated evaluation of the tag in license compliance tools.
See https://maven.apache.org/pom.html#Licenses
Also update the license URL to use https and to avoid a specific file extension.

Use SPDX for Maven license tag

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java

This will use the `LayoutMetaDataService`'s classloader to allow for cases when this JAR and other ELK JARs are loaded in dynamic classloader. 
The previous logic introduced in #789 would only work if the classes were part of the root classloader.  
Closes #1108

Use ELK's classloader, not root classloader to discover services

---

.gitignore
build/.settings/org.eclipse.core.resources.prefs
build/org.eclipse.elk.repository/.settings/org.eclipse.core.resources.prefs
build/org.eclipse.elk.targetplatform/.settings/org.eclipse.core.resources.prefs
docs/.settings/org.eclipse.core.resources.prefs
features/.settings/org.eclipse.core.resources.prefs
features/org.eclipse.elk.libavoid.feature/.settings/org.eclipse.core.resources.prefs
features/org.eclipse.elk.sdk.feature/.settings/org.eclipse.core.resources.prefs
features/org.eclipse.elk.ui.feature/.settings/org.eclipse.core.resources.prefs
plugins/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.alg.libavoid/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.alg.rectpacking/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.alg.topdownpacking/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.core.debug/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.graph.json.text.ide/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.graph.json.text.ui/.settings/org.eclipse.core.resources.prefs
plugins/org.eclipse.elk.graph.json.text/.settings/org.eclipse.core.resources.prefs
test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.common.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.force.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.layered.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.mrtree.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.radial.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.rectpacking.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.spore.test/.settings/org.eclipse.core.resources.prefs
test/org.eclipse.elk.alg.topdown.test/.settings/org.eclipse.core.resources.prefs

In older eclipse versions the default encoding of the workspace depends on the operating system. Therefore different developers may use different encodings. Explicitly set the encoding in all projects and put the related prefs files under version control to make the build reproducible.
This fixes another 25 warnings in the IDE.

Explicitly mark all Eclipse projects as UTF-8

---

.github/workflows/elkjs.yml

once https://github.com/kieler/elkjs/pull/323 is merged the checks for this PR can be rerun and should pass
updates the node versions that we test for elkjs to be on par with the ones elkjs itself builds against

bump node version for tests

---

build/org.eclipse.elk.targetplatform/org.eclipse.elk.targetplatform.target

The wrong orbit release was used in the target platform, but it doesn't seem to break anything. We should fix this inconsistency anyway.

correct targetplatform to use correct orbit release for eclipse 24-09

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/BoxLayoutProvider.java

fixes ticket #866 by taking padding into account when calculating total area.

fixes padding issue of box algorithm

---

plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidLayoutProvider.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java

**Description** 
Large diagrams can take a significant amount of time (more than 1 minute) to complete layout with libavoid. During this process, there is currently no way to cancel the operation. This pull request introduces a minimally invasive change that enables programmatic cancellation of an ongoing layout operation. Please let me know if:
- This aligns with your design choices.
- This PR meets the expectations for how such a change should be implemented.
**Other Considerations**
The PR includes minimal code changes and replicates the existing logic used to close a libavoid server, which the watchdog would use to stop the server if the timeout is exceeded.
A more elegant solution would be to cancel the layout operation via a progress monitor. However, since this change only affects …

libavoidCancelRouting: Add a method that enables canceling of a started layout operation with libavoid

---

plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/GraphvizTool.java
plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/preferences/GraphvizLayouterPreferenceInitializer.java

Replaces the `PROCESS_DEF_TIMEOUT` attribute in the `GraphvizTool` class (changing it from a primitive `int` to `AtomicInteger`) to allow dynamic reconfiguration of the Graphviz executable timeout.
This provides flexibility, especially for users outside an Eclipse environment, while ensuring the modification remains thread-safe.

graphviz.layouter: Making the graphiz executable timeout editable during runtime for non-eclipse user

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/RecursiveGraphLayoutEngine.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/ITopdownSizeApproximator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/TopdownSizeApproximator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/TopdownSizeApproximatorUtil.java

The approximator uses multiple fixed sizes to set sizes for top-down layout according to the number of nodes in a graph. It also lays out two hierarchy levels in one step to keep them at the same scale.
The LAYOUT_NEXT_LEVEL approximator lays out the given graph and sets its algorithm to fixed layout. This allows laying out multiple hierarchy levels in one pass to essentially combine bottom-up and top-down layout.
A new interface ITopdownLayoutApproximator is introduced allowing size approximators to be defined for specific layout algorithms.

Add the fixed integer size approximator

---

plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/ComponentsProcessor.java
test/org.eclipse.elk.alg.mrtree.test/src/org/eclipse/elk/alg/mrtree/test/MrTreeGraphSizeTest.java

Fixes #1140 and https://github.com/kieler/elkjs/issues/294

Recompute graph bounds after packing components in MrTree

---

build/pom.xml

this is following the guide by eclipse: https://eclipse-cbi.github.io/cbi-website/best-practices/github-actions/central-portal/index.html
(not sure if we want autopublish? they list it as best practice)
I think we may still have to add the otterdog config described in there

new config for migration to central

---

plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/formatting2/ElkGraphFormatter.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/GraphTest.xtend

EList.last is deprecated with Java 21. Use lastOrNull instead.

Use lastOrNull instead of last

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java

This issue does only seem to surface once model order allows us to just use the initial graph without changing it.
Fixes #968

Only reorder ports on parent if they changed.
