plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java

Signed-off-by: Ulf Rueegg <uru@informatik.uni-kiel.de>

core: corrected layout option retrieval based on suffixes

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/LayoutConfigurator.java

...leading to a NullPointer on edges.
Signed-off-by: Nis Boerge Wechselberg <enbewe@enbewe.de>

elk.core: Fixed a wrong instanceof check in LayoutConfigurator

---

setups/EclipseLayoutKernel.setup

- Created a second stream to enable work on release version
- Moved git clone task to root level and use stream name for checkout
- Moved Project Import and Working Sets to root level
- Moved elk SDK installation to stream specific level

setup: Created Stream for Release 0.1.1

---

plugins/org.eclipse.elk.graph.text.ui/src/org/eclipse/elk/graph/text/ui/contentassist/ElkGraphProposalProvider.xtend
plugins/org.eclipse.elk.graph/src/org/eclipse/elk/graph/util/ElkGraphUtil.java

This was already implemented for kgraph.text. I mainly adjusted the code to elk.

elk.graph.(text): Reactivated advanced/experimental option values

---

setups/EclipseLayoutKernel.setup

Setup: Added new stream for 0.2.1 release

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk

layered: Allow layerConstraint on nodes

---

plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/jvmmodel/MetaDataJvmModelInferrer.xtend
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutAlgorithmData.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutCategoryData.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutOptionData.java

Introduced builder API for layout meta data

---

plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonExporter.xtend
test/org.eclipse.elk.graph.json.test/src/org/eclipse/elk/graph/json/test/ExportTest.xtend

Signed-off-by: Kristof Slowikowski <ksl@informatik.uni-kiel.de>

graph.json: Fixed exporter issue with portless edges

---

setups/EclipseLayoutKernel.setup

The new release 0.3.0 should have a stream in the oomph setup.

setup: Added release 0.3.0 stream

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelDummySwitcher.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/CenterEdgeLabelPlacementStrategy.java

This pull request implements better layer assignment strategies for center edge labels.

Layered: Improved center edge label layer assignment

---

test/org.eclipse.elk.alg.spore.test/src/org/eclipse/elk/alg/spore/test/ScanlineOverlapRemovalTest.java

spore.test: Fixed imports for generated Spore options

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SplineSelfLoopPreProcessor.java

elk.layered: prevent hiding ports during spline self loop handling

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/LabelAndPortPositionerAndNodeSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeMicroLayout.java
plugins/org.eclipse.elk.alg.force/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/Force.melk
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/ForceLayoutProvider.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/stress/Stress.melk
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/stress/StressLayoutProvider.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/HierarchicalPortOrthogonalEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelAndNodeSizeProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelDummySwitcher.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/NodeMarginCalculator.java
plugins/org.eclipse.elk.alg.mrtree/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/Tree.melk
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/TreeLayoutProvider.java
plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/Radial.melk
plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/RadialLayoutProvider.java
plugins/org.eclipse.elk.alg.spore/src/org/eclipse/elk/alg/spore/ElkGraphImporter.java

Added label and port placement capabilities to further layouters

---

setups/EclipseLayoutKernel.setup

setup: Fixed p2 URL for 0.4.0 stream

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

When junction points are generated in fixed layout, unnecessary bend
points might lead to misplaced junction points. This obviously not
wanted.
```
edgeRouting: ORTHOGONAL
algorithm: fixed
node N1 {
layout [ 
position: 0, 0 
size: 20, 20
]
port P1 {
layout [
position: 20, 7.5
size: 5, 5
]
}
}
node N2 {
layout [
position: 150, 0
size: 20, 20
]
}
node N3 {
layout [
position: 100, 50
size: 20, 20
]
}
edge N1.P1 -> N2 {
layout [
start: 20, 10
end: 150, 10
bends: 40, 10
]
}
edge N1.P1 -> N3 {
layout [
start: 20, 10
end: 100, 60
bends: 80, 10 | 80, 60
]
}
```

ElkUtil: Filter unnecessary bend points in Junction Point calculation

---

plugins/org.eclipse.elk.conn.gmf/plugin.xml

Lower the priority of the GMF layout provider for ELK

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/loops/labeling/SelfLoopLabelPositionEvaluator.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/ElkMath.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/ElkRectangle.java

Replace java.awt.geom.Rectangle2D.Double with ElkRectangle. 

---

plugins/org.eclipse.elk.core.meta.ui/src-gen/org/eclipse/elk/core/meta/ui/AbstractMetaDataUiModule.java
plugins/org.eclipse.elk.core.meta/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.meta/model/generated/MetaData.genmodel
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/AbstractMetaDataRuntimeModule.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdAlgorithmImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdBundleImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdBundleMemberImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdCategoryImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdModelImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdOptionImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MdOptionSupportImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/metaData/impl/MetaDataPackageImpl.java
plugins/org.eclipse.elk.core.meta/src-gen/org/eclipse/elk/core/meta/serializer/MetaDataSemanticSequencer.java
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/GenerateMetaData.mwe2
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/formatting2/MetaDataFormatter.xtend
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.graph.text.ide/META-INF/MANIFEST.MF

Implemented a formatter for the MetaData lanuage in `elk.core.meta`. Needed artifacts were created accordingly.
Issue: #353
Signed-off-by: Daniel Lucas <stu124145@informatik.uni-kiel.de>

Meta: Implemented formatter for MetaData language.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SelfLoopPlacer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SelfLoopPreProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/loops/position/SelfLoopNodePortRestorator.java

Fixed combination of nested graph with external ports and self-loops

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphTransformer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SelfLoopPlacer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SelfLoopPreProcessor.java

Don’t hide ports with fixed position during self-loop processing

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

Include port labels during node scale application, see #430

---

plugins/org.eclipse.elk.core.debug/src/org/eclipse/elk/core/debug/views/graph/LoadGraphAction.java

Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>

Debug: Consider "elk.debug.store" preference in LoadGraphAction

---

plugins/org.eclipse.elk.alg.common/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.disco.debug/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.disco/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.force/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.graphviz.dot/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.graphviz.layouter/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.layered/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.mrtree/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.packing.rectangles/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.radial/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.alg.spore/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.conn.gmf/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.conn.graphiti/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug.grandom.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug.grandom.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug.grandom/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.meta.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.meta/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.service/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.json/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.text.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.text.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph.text/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.graph/META-INF/MANIFEST.MF

Added Automatic-Module-Name to all manifests. #429

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LPort.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PortSideProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/SweepCopy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/loops/position/SelfLoopNodePortRestorator.java

While fixing the bug. The anchorFixed variable was refactored and renamed to explicitlySuppliedPortAnchor and request of cds.

Fixed northOrSouth port anchor bug. #411

---

plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/rendering/GraphRenderer.java
plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/rendering/GraphRenderingCanvas.java
plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/rendering/GraphRenderingConfigurator.java
plugins/org.eclipse.elk.core.ui/src/org/eclipse/elk/core/ui/rendering/LayoutGraphDialog.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/KVector.java

This makes it easier to navigate large graphs. I'm using it in the LayoutGraphDialog (shown when invoking layout on an elkt file), but not yet for the Layout Graph view. It would be easy to use the new functionality in that view, too.

Implemented zooming and panning for GraphRenderingCanvas

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/BasicProgressMonitor.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/IElkProgressMonitor.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/LoggedGraph.java
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImportException.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonMetaDataConverter.xtend

Not yet ready to merge - I fixed a number of issues. See below for more. 
@le-cds feel free to fix the issues and change the current fixes if you see a better way. 
Also, I added a `TODO` where a statement seemed to have no effect. Can you please double check that?
```
[ERROR] Errors in 'file:/workspace/elkjs/build/src/elk/org/eclipse/elk/core/util/ElkUtil.java'
[ERROR] Line 1013: No source code is available for type java.util.regex.Pattern; did you forget to inherit a required module?
[ERROR] Errors in 'file:/workspace/elkjs/build/src/elk/org/eclipse/elk/core/util/BasicProgressMonitor.java'
[ERROR] Line 477: The method format(String, long, char, char, String) is undefined for the type String
[ERROR] Line 499: The method format(String, int, String) is undefined for the type String
```

Changes towards GWT compatibility

---

plugins/org.eclipse.elk.alg.disco.debug/build.properties

alg.disco.debug: Fix view icon not included

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LayerSizeAndGraphHeightCalculator.java

Consider port spacing when calculating graph height

---

plugins/org.eclipse.elk.alg.packing.rectangles/build.properties

Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>

Rectangle.Packing: Add class files in built jar file

---

plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/NodeLabelAndSizeCalculator.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/cellsystem/LabelCell.java
plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/NodeLabelCellCreator.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue476Test.java

Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>

Core: Fix multi-label alignment in vertical layout. #476

---

plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/RectPackingLayoutProvider.java
plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/firstiteration/ScaleMeasureFilter.java
plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/Compaction.java
plugins/org.eclipse.elk.alg.packing.rectangles/src/org/eclipse/elk/alg/packing/rectangles/seconditeration/RowFillingAndCompaction.java

Issue #483: RectPacking: Initialize values with MIN_VALUE instead of -Infinity.

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/adapters/ElkGraphAdapters.java

@le-cds as discussed via phone

fix of potential NPE in 'ElkGraphAdapters'

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/ConstraintsPostprocessor.java

Excluded debug output from elkjs build

---

plugins/org.eclipse.elk.core.service/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.service/pom.xml

* added description
* added maven dependencies
* refined dependencies in META-INF/MANIFEST.MF

Service: dropped exclusion while publishing to maven central

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPackingLayoutProvider.java
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/firstiteration/AreaApproximation.java
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/seconditeration/RowFillingAndCompaction.java

Node expansion considers the minimum size of the parent.

---

plugins/org.eclipse.elk.core.service/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/LayoutConnectorsService.java

@le-cds Unfortunately I spotted the issue fixed here while you were preparing 0.6.1.
What about a quick 0.6.2 😬?

Service: two minor changes facilitating usage without a running eclipse platform

---

plugins/org.eclipse.elk.alg.graphviz.dot/src/org/eclipse/elk/alg/graphviz/dot/formatting2/GraphvizDotFormatter.xtend
plugins/org.eclipse.elk.alg.radial/META-INF/MANIFEST.MF
plugins/org.eclipse.elk.core.debug.grandom.ui/src/org/eclipse/elk/core/debug/grandom/ui/GRandomHandler.xtend
plugins/org.eclipse.elk.core.debug.grandom/src/org/eclipse/elk/core/debug/grandom/validation/GRandomValidator.xtend
plugins/org.eclipse.elk.core.meta.ui/src/org/eclipse/elk/core/meta/ui/outline/MetaDataOutlineTreeProvider.xtend
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/formatting2/MetaDataFormatter.xtend
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/jvmmodel/MelkDocumentationGenerator.xtend
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/jvmmodel/MetaDataJvmModelInferrer.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonAdapter.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonExporter.xtend
plugins/org.eclipse.elk.graph.text.ide/src/org/eclipse/elk/graph/text/ide/contentassist/ElkGraphProposalProvider.xtend
test/org.eclipse.elk.core.test/META-INF/MANIFEST.MF

Simply went through the compilation log and removed almost all apparent warnings.

Removed compiler warnings

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/ForsterConstraintResolver.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/InLayerConstraintProcessorTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p3order/counting/AllCrossingsCounterTest.java
test/org.eclipse.elk.graph.json.test/pom.xml

* removed a syso
* fixed a broken test (see commit message)
* allow `AllCrossingsCounterTest` to be executed as plain junit test
* actually build xtend-based tests for graph.json.test

Minor fixes to the tests

---

build/pom.xml
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p4nodes/NetworkSimplexPlacer.java

In particular, fixes two issues of #540.

Further fixes to tests

---

plugins/org.eclipse.elk.graph.text.ide/src/org/eclipse/elk/graph/text/ide/contentassist/ElkGraphProposalProvider.xtend
plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/conversion/PropertyKeyValueConverter.xtend
plugins/org.eclipse.elk.graph.text/src/org/eclipse/elk/graph/text/validation/ElkGraphValidator.xtend

See individual commit messages for details.

Minor adjustments to elkt's tooling

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk

Somehow `layered.melk` slipped through converting tabs to spaces in the original PR.

Amendment to #582

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/GraphTransformer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue405Test.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue405_2Test.java

Fixes #405 (invalid port label positions)

---

docs/content/documentation/tooldevelopers/graphdatastructure/layoutoptions.md
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphUtil.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue546Test.java

Fixes #546

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPacking.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java
test/org.eclipse.elk.core.test/src/org/eclipse/elk/core/util/ElkUtilTest.java

Add tests for ElkUtil translate with content alignment

---

plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/Graphviz.melk
plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/RectPacking.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

I renamed the following algorithms:
| Old               | New                   |
| ----------------- | --------------------- |
| Box Layout        | ELK Box               |
| FixedLayout       | ELK Fixed             |
| Randomizer        | ELK Randomizer        |
| Rectangle Packing | ELK Rectangle Packing |

[PR] More consistent layout algorithm names

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/NorthSouthPortPreprocessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/SweepCopy.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/AllowNonFlowPortsToSwitchSidesTest.java

See #605 for details and discussion.

[PR] Rename northOrSouthPort option

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java

Signed-off-by: Christoph Daniel Schulze <cds@informatik.uni-kiel.de>

[PR] Layered: Proper error message for invalid hierarchical edges. #588

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/CommentNodeMarginCalculator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/CommentPostprocessor.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

Signed-off-by: Christoph Daniel Schulze <cds@informatik.uni-kiel.de>

[PR] Layered: Comment-related spacings are now inherited. #594

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/DebugUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/DotDebugUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/JsonDebugUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/HierarchicalPortOrthogonalEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/loops/routing/RoutingSlotAssigner.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/OrthogonalEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeCycleBreaker.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeCycleDetector.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeSegment.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeSegmentDependency.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeSegmentSplitter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/OrthogonalRoutingGenerator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/direction/BaseRoutingDirectionStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/direction/NorthToSouthRoutingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/direction/RoutingDirection.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/direction/SouthToNorthRoutingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/direction/WestToEastRoutingStrategy.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue143And318Test.java

This pull request fixes #143 and #318.
**Review notes**
The first commit is simply refactoring. The remaining ones are probably best to review in order.
Due to popular request, here are two screenshots of what this does. If edges come too close (#143), this happens:
If edges would overlap (#318), this happens:

[PR] Layered: Prevent edge overlaps.

---

plugins/org.eclipse.elk.alg.graphviz.layouter/pom.xml
plugins/org.eclipse.elk.alg.mrtree/pom.xml
plugins/org.eclipse.elk.alg.spore/pom.xml

[PR] Removed outdated xtend build workarounds

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/GreedySwitchType.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue628Test.java

See #628 for details and discussion.

[PR] Correctly configure greedy switch during hierarchical layout

---

plugins/org.eclipse.elk.alg.graphviz.dot/src/org/eclipse/elk/alg/graphviz/dot/transform/DotExporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/GmfDiagramLayoutConnector.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/options/EdgeLabelPlacement.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/ElkUtil.java

[PR] Remove undefined edge label placement

---

plugins/org.eclipse.elk.alg.common/pom.xml
plugins/org.eclipse.elk.alg.disco/pom.xml
plugins/org.eclipse.elk.alg.force/pom.xml
plugins/org.eclipse.elk.alg.layered/pom.xml
plugins/org.eclipse.elk.alg.radial/pom.xml
plugins/org.eclipse.elk.alg.rectpacking/pom.xml
plugins/org.eclipse.elk.conn.gmf/pom.xml
plugins/org.eclipse.elk.core/pom.xml

Follow-up PR to #658. I thought I double checked, but obviously I missed several further outdated workarounds.
@markxiaotao FYI.

[PR] (2) Removed outdated xtend build workarounds

---

docs/content/downloads/releasenotes/release-0.7.0.md

This pull request starts work on the release notes for 0.7.0. It's a draft as long as we keep fixing issues. However, please check whether I've missed anything or if you can make anything clearer or more informative.

[PR] [WIP] Docs: Started writing release notes.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/GraphTransformer.java
test/org.eclipse.elk.alg.layered.test/META-INF/MANIFEST.MF
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue682Test.java

[PR] Correct node labels padding when direction is not RIGHT

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/SortByInputModelProcessor.java

layered: Cache port sides after sorting ports #696

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

[PR] core: Document content alignment properly #688

---

docs/config.toml
plugins/org.eclipse.elk.core.meta/src/org/eclipse/elk/core/meta/jvmmodel/MelkDocumentationGenerator.xtend

[PR] Melk: Fix wrong dependency links. #718

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue700Test.java

Layered: Fix wrong hierarchy handling. #700

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/PolylineEdgeRouter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/splines/SplineEdgeRouter.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue587Test.java

[PR] Layered: Fixed NPE in polyline and spline edge routers. #587

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/OrthogonalEdgeRouter.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/issues/Issue734Test.java

[PR] Unexpected variation in edge-node spacing

---

plugins/org.eclipse.elk.core.service/pom.xml

core.service: build: temporarily exclude 'javax.annotation-api'

---

test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizerTest.java

Signed-off-by: Steve Kieffer <steve.kieffer@runbox.com>

Tests: supply a missing test setup step.

---

plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/GraphvizLayoutProvider.java

Graphviz: Prevent call to eclipse UI if no platform is running.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java

Layered: Added fixed graph size support.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/GraphConfigurator.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk

Layered: Add option to generate position and layer ids.

---

docs/content/documentation/tooldevelopers/graphdatastructure/layoutoptions.md
docs/content/documentation/tooldevelopers/graphdatastructure/layoutoptions/spacingdocumentation.md

Added spacing documentation.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/Layered.melk
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/ComponentsProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphUtil.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java

Layered: Added separate option to order components by model order.

---

docs/layouts/index.html
docs/layouts/partials/navbar.html

Added trademark to project website.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/CycleBreakingStrategy.java

layered: Actually create greedy model order cycle breaker.

---

test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p3order/BarycenterHeuristicTest.java

test: Init ElkReflect in failing BarycenterHeuristicTest.

---

docs/content/downloads/releasenotes/release-0.8.1.md

Release: Added 0.8.1 release notes.

---

plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.force/src/org/eclipse/elk/alg/force/Force.melk
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.mrtree/src/org/eclipse/elk/alg/mrtree/Tree.melk

add fixedGraphSize support for mrtree and force based layout

---

.gitignore
.gitpod.Dockerfile
.gitpod.yml
docs/content/documentation/contributors/buildingelk.md

As requested in #857, feel free to correct the gitpod setup.

Gitpod for Website

---

docs/content/blog/_index.md
docs/content/blog/posts/2022/22-08-31-rectpacking.md
docs/content/blog/posts/2022/22-11-17-libavoid.md

I wrote a short post about the new libavoid integration.

Created blog post about libavoid

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java

Fix ClassCastException during Layout

---

docs/content/gettingstarted/_index.md

Update getting started information.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/BiLinkedHashMultiMap.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/NodePromotion.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayeringStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/NodePromotionStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers/LongestPathSourceLayerer.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/intermediate/NodePromotionTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p2layers/BasicLayerAssignmentTest.java
test/org.eclipse.elk.alg.layered.test/src/org/eclipse/elk/alg/layered/p2layers/ModelOrderLayerAssignmentTest.java

Added simple layer assignment strategies as well as a model order node promoter.

Model Order layer assingment

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/ComponentOrderingStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/ComponentsProcessor.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/ModelOrderRowGraphPlacer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/components/SimpleRowGraphPlacer.java

Added a component graph row placer that considers model order by introducing new rows if the order dictates it.

layered: Added component model order row placer.

---

plugins/org.eclipse.elk.alg.radial/docs/radial.md

Fixes some typos and improves readability of Radial layout documentation.

Radial documentation.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LGraphAdapters.java

Fixes #850
@Eddykasp Please have a look at this.

layered: Return self loop edges while checking for label next to port.

---

plugins/org.eclipse.elk.alg.libavoid/pom.xml

Changed the libavoid server version to the new build that supports hyperedges and clusters.

Updated libavoid server version

---

build/org.eclipse.elk.repository/category.xml

Thank @lredor for pointing this out.
https://github.com/eclipse-pde/eclipse.pde/issues/1014#issuecomment-1857989584

Remove hopefully unnecessary eclipse mars and guava svn for category.xml.

---

plugins/org.eclipse.elk.alg.force/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.graphviz.dot/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.layered/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.mrtree/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.rectpacking/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.alg.topdownpacking/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.conn.gmf/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.debug/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core.service/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.elk.core/.settings/org.eclipse.jdt.core.prefs

Thanks @Skgland for pointing this out.

Remove merge conflict markers.

---

build/Jenkinsfile

remove website and update site upload from jenkinsfile

---

build/Jenkinsfile
build/pom.xml
plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/ElkLayoutProvider.java

Fixed #1011 issue with maven plugins.
And other minor fixes.

Fixes for elk 0.9.1 release

---

plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/Libavoid.melk
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java

add timeout property to libavoid

---

plugins/org.eclipse.elk.alg.disco/src/org/eclipse/elk/alg/disco/DisCoPolyominoCompactor.java

~~This may help with the failing elkjs build~~
Updates deprecated API usage

Replace deprecated Double constructor

---

plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk

Option for https://github.com/kieler/KLighD/pull/218

add fuzziness property for label softwrapping

---

plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonAdapter.xtend
plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend

together with https://github.com/kieler/elkjs/pull/316 hopefully fixes #1001

remove old edge sections and update jsonwrapper

---

.editorconfig

Keep whitespace in files to prevent unintended changes in PRs

---

plugins/org.eclipse.elk.alg.rectpacking/src/org/eclipse/elk/alg/rectpacking/intermediate/MinSizePreProcessor.java

This fixes #1153 
@Eddykasp I would like to see this merged quickly to do a elkjs service release.

Consider the parent label when having child nodes for size.

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/CrossingMinimizationStrategy.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/InternalProperties.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/BarycenterHeuristic.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/GraphInfoHolder.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/LayerSweepCrossingMinimizer.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p3order/MedianHeuristic.java

Implemented a Median Heuristic that works similarly to the Barycenter Heuristic. Added the appropriate option called
crossingMinimization.strategy: MEDIAN_LAYER_SWEEP

Median Heuristic implemented

---

docs/content/documentation/tooldevelopers/graphdatastructure/elktextformat.md

fixes https://github.com/eclipse-elk/elk/issues/1133

Add documentation about the ELK text format

---

plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/LPadding.java
plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java
plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/KVectorChain.java

Add helper methods to log an LGraph.

---

docs/content/blog/2024.md
docs/content/blog/2025.md
docs/content/blog/_index.md
docs/content/blog/posts/2024/24-12-06-layer-unzipping.md
docs/content/blog/posts/2025/25-08-21-layered.md
docs/static/img/layered-algorithm-structure.svg

I want to briefly explain what each layout phase does and how to configure that.
Additionally, I fixed problems in older blogposts such that they are correctly displayed.

Add ELK Layered Blog Post
